load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "task",
    srcs = ["task.go"],
    importpath = "github.com/yishuiliunian/nexusapi/backend/internal/interface/http/task",
    visibility = ["//backend:__subpackages__"],
    deps = [
        "//backend/internal/app/keys",
        "//backend/internal/app/task",
        "//backend/internal/interface/http/middleware",
        "//backend/pkg/errors",
        "//backend/pkg/httperr",
        "@com_github_gin_gonic_gin//:gin",
    ],
)
