load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "queue",
    srcs = [
        "queue.go",
        "tasks.go",
    ],
    importpath = "github.com/yishuiliunian/nexusapi/backend/internal/infra/queue",
    visibility = ["//backend:__subpackages__"],
    deps = [
        "@com_github_hibiken_asynq//:asynq",
    ],
)
