# shellcheck shell=bash
# config_gen.sh — .env 与前端 .env.local 生成。
#
# .env 是端口、密码、project 名的 SSOT（single source of truth）。
# 二次运行时检测到 COMPOSE_PROJECT_NAME 匹配则保留旧值，保证：
#   - 外部工具引用稳定（已注册的 OAuth callback、本地书签）
#   - dev.sh 反复跑不会改端口
#
# 端口分配（base=20000，步长 50）：
#   slot 0  backend HTTP
#   slot 1  upstream-mock
#   slot 2  web-user
#   slot 3  web-admin
#   slot 4  postgres
#   slot 5  redis
#   slot 6  adminer（可选 UI）
#   slot 7-9 预留

generate_env() {
    local worktree_name
    worktree_name=$(get_worktree_name)
    local project_name="nexusapi-${worktree_name}"

    # 幂等：已存在且 project name 匹配则 source 后返回
    if [[ -f "$ENV_FILE" ]] && grep -q "COMPOSE_PROJECT_NAME=$project_name" "$ENV_FILE"; then
        # shellcheck disable=SC1090
        source "$ENV_FILE"
        WORKTREE_NAME="$worktree_name"
        PORT_OFFSET=$(( (BACKEND_PORT - 20000) / 50 ))
        export WORKTREE_NAME PORT_OFFSET
        success "保留现有 .env (worktree: $worktree_name, backend: :$BACKEND_PORT)"
        return 0
    fi

    local offset
    offset=$(calculate_port_offset "$worktree_name")
    WORKTREE_NAME="$worktree_name"
    PORT_OFFSET="$offset"
    export WORKTREE_NAME PORT_OFFSET

    local backend_port=$((20000 + offset * 50))
    local upstream_port=$((20001 + offset * 50))
    local web_user_port=$((20002 + offset * 50))
    local web_admin_port=$((20003 + offset * 50))
    local postgres_port=$((20004 + offset * 50))
    local redis_port=$((20005 + offset * 50))
    local adminer_port=$((20006 + offset * 50))

    cat > "$ENV_FILE" <<EOF
# NexusAPI Dev Environment - Auto-generated by deploy/dev/dev.sh
# Worktree: $worktree_name | Offset: $offset

COMPOSE_PROJECT_NAME=$project_name
WORKTREE_NAME=$worktree_name
PORT_OFFSET=$offset

# =============================================================================
# Ports（base=20000，步长 50，main worktree=offset 0）
# =============================================================================
BACKEND_PORT=$backend_port
UPSTREAM_PORT=$upstream_port
WEB_USER_PORT=$web_user_port
WEB_ADMIN_PORT=$web_admin_port
POSTGRES_PORT=$postgres_port
REDIS_PORT=$redis_port
ADMINER_PORT=$adminer_port

# =============================================================================
# Postgres 凭证（容器内 / 主机连接都用）
# =============================================================================
POSTGRES_USER=nexusapi
POSTGRES_PASSWORD=nexusapi_dev
POSTGRES_DB=nexusapi

# =============================================================================
# Backend 配置（host 启动时通过 NEXUSAPI_* 环境变量注入）
# =============================================================================
NEXUSAPI_DATABASE_DRIVER=postgres
NEXUSAPI_DATABASE_DSN=postgres://nexusapi:nexusapi_dev@127.0.0.1:$postgres_port/nexusapi?sslmode=disable
NEXUSAPI_REDIS_ADDR=127.0.0.1:$redis_port
NEXUSAPI_SECURITY_ENCRYPTION_KEY=
NEXUSAPI_SITE_BASE_URL=http://127.0.0.1:$web_user_port
EOF
    success "生成 .env (worktree: $worktree_name, backend: :$backend_port)"
}

# generate_web_env 同步前端 .env.local（user + admin），让前端走 SSR 时
# 知道 backend 在哪。变量名沿用项目既有的 NEXUSAPI_BACKEND_URL。
generate_web_env() {
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    local user_env="$SCRIPT_DIR/../../web-user/.env.local"
    local admin_env="$SCRIPT_DIR/../../web-admin/.env.local"

    cat > "$user_env" <<EOF
# Auto-generated by deploy/dev/dev.sh — worktree: $WORKTREE_NAME
NEXUSAPI_BACKEND_URL=http://127.0.0.1:$BACKEND_PORT
EOF
    cat > "$admin_env" <<EOF
# Auto-generated by deploy/dev/dev.sh — worktree: $WORKTREE_NAME
NEXUSAPI_BACKEND_URL=http://127.0.0.1:$BACKEND_PORT
EOF
    success "生成 web-user/.env.local + web-admin/.env.local"
}
